services:
  mattermost:
    image: mattermost/mattermost-team-edition
    container_name: mattermost
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db/mattermost?sslmode=disable
    ports:
      - "8065:8065"
    depends_on:
      - db
    volumes:
      - ./mattermost/config:/mattermost/config
      - ./mattermost/data:/mattermost/data
      - ./mattermost/logs:/mattermost/logs
      - ./mattermost/plugins:/mattermost/plugins
      - ./mattermost/client-plugins:/mattermost/client/plugins
    networks:
      - mattermost-net

  db:
    image: postgres:15
    container_name: mattermost-db
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    networks:
      - mattermost-net

  app-db:
    image: postgres:15
    container_name: app-db
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=appuser_password
      - POSTGRES_DB=appdb
    networks:
      - mattermost-net

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    networks:
      - mattermost-net
    depends_on:
      - mattermost
      - app-db

networks:
  mattermost-net:
    driver: bridge